# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  macos:
    runs-on: macos-15

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.1.0"

      - uses: actions/checkout@v3

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: SwiftyLab/setup-swift@latest
      - name: Get swift version
        run: swift --version

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: SwiftyLab/setup-swift@latest
      - name: Get swift version
        run: swift --version

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test
